language: python
python:
  - "3.3"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script: 
  nosetests --all-modules --traverse-namespace --with-coverage --cover-package=puckman --cover-inclusive
after_success:
  coveralls

